CREATE DATABASE IF NOT EXISTS crm;

USE crm;

DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS auth_token;
DROP TABLE IF EXISTS user;

DROP EVENT IF EXISTS cleanup_auth_tokens;

CREATE TABLE user
(
    username VARCHAR(100) NOT NULL PRIMARY KEY,
    password VARCHAR(64) NOT NULL
);

CREATE TABLE auth_token
(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    token VARCHAR(128) NOT NULL,
    FOREIGN KEY (username) REFERENCES user (username) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE customer
(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    last_name VARCHAR(600) NOT NULL,
    first_name VARCHAR(600),
    company_name VARCHAR(500),
    email VARCHAR(300) NOT NULL,
    street_address TEXT,
    city VARCHAR(200),
    state VARCHAR(10),
    postal_code VARCHAR(25),
    phone VARCHAR(50),
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES user (username) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE EVENT cleanup_auth_tokens
ON SCHEDULE EVERY 10 MINUTE
DO
DELETE FROM auth_token
WHERE created_at <= DATE_SUB(NOW(), INTERVAL 1 HOUR);